### PR TITLE
Wait queue

### LINKED ISSUE #13: Format messages in failure queue so that they can be re-processed by reconfiguring the env vars
Just need to make sure they have a {"filename":"xxx"} value in the json structure, which I think we still have available in the various failure cases.

### LINKED ISSUE #15: Change message loop to process one event a time and wait for completion before removing it from queue.
With a heavy load in testing today (>300 events), we ran out of memory on the EC2 instance due to and overload of ffmpeg processes (there were ~115 concurrent ffmpeg processes when it started to fail). 

Investigate whether we should instead wait on the ffmpeg (and subsequent S3 upload) to complete before we move on to the next event. This will slow down the overall queue processing but will conserve system resources. A delay before the opus files are made available (even a delay of several minutes) should be acceptable.

### PR DESCRIPTION
**Pull request by dylano**
Fixes #13 
Fixes #15 

Processes one message at a time from the queue and waits for it to succeed before removing it from the queue. 

* Added `transcodeInProgress` var to prevent the launch of multiple ffmpeg processes. this is useful for large files when the message loop pulls the same message off the queue again
* Added the {filename} value to the messages which are placed in the failure queue. This enables an easy way to retry failed events by pointing the process at the failure queue and restarting. 

Note: for long transcode processes (i.e. those that take longer than the queue's `VisibilityTimeout` setting), the message handle goes stale and removing the message from the queue with that handle will produce an error. This situation will get resolved on the next trip through the queue when we get a fresh handle

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -44,51 +44,53 @@ const failQueue = new SqsQueue(failureQueueURL, 'scout');
...
-                storeFile(newFileName);
-              })
-              .catch(err => {
+          // create transcode request if the file doesn't already exist
+          if (jsonBody && jsonBody.filename) {
+            logger.info(`Received message with filename: ${jsonBody.filename}`);
+            const fileExists = await checkFileExistence(jsonBody.filename);
+            if (!fileExists) {
+              try {
+                transcodeInProgress = true;
```
Comment (tamarahills) [inline index.js]: Is this the right place to set the flag to true?  Could another one sneak in before this?

Comment (dylano) [reply index.js]: Since we're just processing one message at a time, I don't _think_ another request will get in there.  I guess we could pull it higher in the function and make it a more generic `messageInProgress`.
